# https://github.com/alibaba/nacos
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Github CI for Nacos Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
  schedule:
    -
      cron: 0 18 1/7 * *

env:
  NACOS_REF: 'develop'
  APPLICATION: 'nacos'

jobs:
  Nacos-Dokcer-Builder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.2.0

    - name: Set Environment Variables
      run: |
        timestamp=`date '+%Y%m%d'`
        echo 'TIMESTAMP='$timestamp >> $GITHUB_ENV

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    # checkout nacos
    - uses: actions/checkout@v2.2.0
      with:
        repository: alibaba/nacos
        ref: 'develop'
        path: nacos

    # build nacos server
    - name: Build with Maven
      run: |
        cd ${{ github.workspace }}/nacos
        mvn -Prelease-nacos -Dmaven.test.skip=true -Dcheckstyle.skip=true -Drat.numUnapprovedLicenses=1024 clean install -U --file pom.xml
   
    # copy nacos server
    - name: Copy Nacos Artifact
      run: |
        cd ${{ github.workspace }}
        mkdir -p build/artifact
        mv nacos/distribution/target/*.tar.gz build/artifact/
        name=`ls build/artifact/ |head -n1`
        t=`echo ${name##*server-}`
        version=`echo ${t%%.tar*}`
        echo 'VERSION='$version >> $GITHUB_ENV
    
        
    # build docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}/build/
        build-args: |
          NACOS_VERSION=${{ env.VERSION }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APPLICATION }}:${{ env.VERSION }}-${{ env.TIMESTAMP }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APPLICATION }}:latest
